# Generated by Django 3.0.6 on 2020-07-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200705_0318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animais',
        ),
    ]
