# Generated by Django 3.0.6 on 2020-07-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_animais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URSO', models.CharField(choices=[('false', 'false'), ('true', 'true')], max_length=7)),
                ('LEAO', models.CharField(choices=[('false', 'false'), ('true', 'true')], max_length=7)),
                ('ELEFANTE', models.CharField(choices=[('false', 'false'), ('true', 'true')], max_length=7)),
                ('GIRAFA', models.CharField(choices=[('false', 'false'), ('true', 'true')], max_length=7)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Palavra',
        ),
    ]
