# Generated by Django 3.0.6 on 2020-07-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_animais_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animais',
            name='ELEFANTE',
        ),
        migrations.RemoveField(
            model_name='animais',
            name='GIRAFA',
        ),
        migrations.RemoveField(
            model_name='animais',
            name='LEAO',
        ),
        migrations.RemoveField(
            model_name='animais',
            name='URSO',
        ),
        migrations.AddField(
            model_name='animais',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
