# Generated by Django 3.0.6 on 2020-07-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200705_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
